<?php
/**
 * Customer Example Template
 *
 * @category   Certification
 * @package    Certification_CustomerManagementMyAccount
 * @author     Andresa Martins <contact@andresa.dev>
 * @license    http://opensource.org/licenses/BSD-2-Clause Simplified BSD License
 */

/** @var Certification\CustomerManagementMyAccount\Block\Customer\Example $block */

?>

<p><b>Full Name: </b><?= $block->getFullName(); ?></p>
<p><b>E-mail: </b><?= $block->getEmail(); ?></p>